### PR TITLE
Added automatic installation with Chef

### PR DESCRIPTION
**Pull request by pietervogelaar**

### CODE REVIEW

**Comment by pietervogelaar** [comment]
Any update on this?

**Comment by pietervogelaar** [comment]
Hi Sebastian, please merge this pull request if you find it okay like this. Thanks!

**Comment by thorsten** [comment]
Why only mention Chef, if there's also Puppet, Ansible, Saltstack and so on...

**Comment by pietervogelaar** [comment]
If there are good cookbooks for those configuration management systems, feel free to add!

**Pull request closed without merging**
